export const defaultValues = {
    // this is for table of sensitivity_device table
    device_name: "",
    rom: "",
    ram: "",
    screen_resolution: "",
    slug: "",
    intro: false,
    camera: false,
    ads: false,
    gyroScope: false,
    explanation: "",
    claws: false,
    intro_text: "",
    proccessor: "",
    // this is for table of sensitivites
    tpp_no_scope: "",
    fpp_no_scope: "",
    red_dot: "",
    "2x_scope": "",
    '3x_scope': "",
    '4x_scope': "",
    '6x_scope': "",
    '8x_scope': "",
    ads_tpp_no_scope: "",
    ads_fpp_no_scope: "",
    ads_red_dot: "",
    ads_2x: "",
    ads_3x: "",
    ads_4x: "",
    ads_6x: "",
    ads_8x: "",
    gyro_tpp_no_scope: "",
    gyro_fpp_no_scope: "",
    gyro_red_dot: "",
    gyro_2x: "",
    gyro_3x: "",
    gyro_4x: "",
    gyro_6x: "",
    gyro_8x: "",
    freelook_camera_tpp: "",
    freelook_camera_parachuting: "",
    freelook_camera_fpp_character: "",
}